services:
  - type: web
    name: n8n
    env: docker
    region: frankfurt  # Optional (defaults to oregon)
    plan: free  # Optional (defaults to starter)
    branch: main  # Optional (defaults to master)
    numInstances: 1
    healthCheckPath: /healthz

    # --- Variables d'environnement ---
    envVars:
      # Configuration de la base de données (PostgreSQL)
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nDB
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password

      # Configuration de base de n8n
      - key: PORT
        value: "5678"
      - key: N8N_LOG_LEVEL
        value: "info"
      - key: GENERIC_TIMEZONE
        value: "Europe/Paris"
      - key: TZ
        value: "Europe/Paris"
      - key: N8N_DEFAULT_LOCALE
        value: "fr"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Activation des nœuds et packages communautaires
      - key: N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE
        value: "true"

      # Configuration des task runners
      - key: N8N_RUNNERS_ENABLED
        value: "true"

      # Configuration des permissions
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

# --- Base de données ---
databases:
  - name: n8nDB
    region: frankfurt  # Optional (defaults to oregon)
    plan: free